apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rds-mysql-secret
  namespace: prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: rds-mysql-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: rds!db-1eb84d09-d792-4e43-a87d-fd29c5c46733
